Repository JuliaEditorSupport/zed-julia, pull requests merged in 2024-09, with the labels that each got.

#12 Docstrings on lone identifiers and SQLStrings language injection
  languages/julia/highlights.scm
  languages/julia/injections.scm
  syntax-test-cases/docstrings.jl
Labels: enhancement, queries

#13 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#18 Docstrings on annotated definitions + on strings stolen by preceding top level macros
  languages/julia/highlights.scm
  languages/julia/injections.scm
  syntax-test-cases/docstrings.jl
Labels: external:tree-sitter, queries
